### PR TITLE
added bio for jerome.

### PR DESCRIPTION
**Pull request by amosdesigns**

### CODE REVIEW

**Comment by charlotteesears** [comment]
@amosdesigns What is your favorite kind of food? Can you add please?

**Comment by amosdesigns** [comment]
my favor kind of food is good food. but if you live to understand the type that I have cooked please check this link out.  http://savoryscrapbook.com.

**Comment by charlotteesears** [comment]
LGTM :+1:

**Comment by charlotteesears** [comment]
Whoa, bookmarking that site

**Pull request closed without merging**
