### PR TITLE
Added bio for Siddhartha Sandhu

### PR DESCRIPTION
**Pull request by siddharthasandhu**
nyccamp.org

### CODE REVIEW

**Comment by amosdesigns** [comment]
hey @siddharthasandhu , how long have you lived in NYC?

**Comment by siddharthasandhu** [comment]
Hey @amosdesigns I have been here 5 days!

**Comment by amosdesigns** [comment]
LGTM :+1:

**Comment by siddharthasandhu** [comment]
@amosdesigns :+1: Cant see your thumb though!

**Comment by amosdesigns** [comment]
LGTM :+1

**Pull request closed without merging**
